- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "torkel.aannestad@outlook.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Torkel Aannestad"
  tags:
  - git-personal

